version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules_{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --production=false
      - save_cache:
          paths:
            - node_modules
          key: node_modules_{{ checksum "package.json" }}
      - run:
          name: Perform Tests
          command: |
            yarn run nyc --reporter=text ava --verbose test/**/*.test.js
      - run:
          name: Generate Code Coverage Report
          command: |
            yarn run nyc report --reporter=text-lcov > coverage.lcov && yarn run codecov
