version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules_{{ checksum "package.json" }}
      - run: |
        yarn install --production=false
        yarn add ava tap-xunit --dev # only for circleci env
      - save_cache:
          paths:
            - node_modules
          key: node_modules_{{ checksum "package.json" }}
      - run: yarn run nyc --reporter=text ava --tap test/**/*.test.js | tap-xunit > ava.xml
      - run: yarn run nyc report --reporter=text-lcov > coverage.lcov && yarn run codecov
      - store_test_results:
          path: ava.xml
